### ISSUE TITLE
The DLL files are missing

### ISSUE THREAD

**Issue by montuIO** [kulek1/Geluid#12]
Trying to run the program and trying to build it, but I keep getting the same error message "The DLL files are missing. Sit back while we build them for you with "npm run build-dll"

I downloaded the zip file and installed npm and yarn into the app folder and tried running the commands.

**Comment by kulek1** [comment]
What's your OS? Can you attach the console output?

`npm` and `yarn` shouldn't be inside app folder.

**Comment by codedbean** [comment]
I'm running this on MacOS 10.14.5

```
Uncaught Exception:
/Users/user/Desktop/audio/app/index.js:1
import React from 'react';
       ^^^^^

SyntaxError: Unexpected identifier
    at Module._compile (internal/modules/cjs/loader.js:752:23)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:827:10)
    at Module.load (internal/modules/cjs/loader.js:677:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:609:12)
    at Function.Module._load (internal/modules/cjs/loader.js:601:3)
    at loadApplicationPackage (/Users/user/Desktop/audio/node_modules/electron/dist/Electron.app/Contents/Resources/default_app.asar/main.js:107:12)
    at Object.<anonymous> (/Users/user/Desktop/audio/node_modules/electron/dist/Electron.app/Contents/Resources/default_app.asar/main.js:155:5)
    at Module._compile (internal/modules/cjs/loader.js:815:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:827:10)
    at Module.load (internal/modules/cjs/loader.js:677:32)
```

**Comment by codedbean** [comment]
```User:audio user$ yarn build client
yarn run v1.16.0
$ concurrently "npm run build-main" "npm run build-renderer" client
/bin/sh: concurrently: command not found
error Command failed with exit code 127.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
User:audio user$ yarn dev
yarn run v1.16.0
$ cross-env START_HOT=1 node -r babel-register ./internals/scripts/CheckPortInUse.js && cross-env START_HOT=1 npm run start-renderer-dev
/bin/sh: cross-env: command not found
error Command failed with exit code 127.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
User:audio user$ 
```

**Comment by kulek1** [comment]
Please, run `yarn` to install dependencies then `yarn dev` to build and run the app.

**Comment by codedbean** [comment]
Still get the same error as the previous comment.

**Comment by kulek1** [comment]
It looks like you didn't run `yarn` or `yarn install` command.
Do you have `node_modules` inside this directory?

**Comment by codedbean** [comment]
Yes, I have node_modules inside the directory.

**Comment by kulek1** [comment]
The output said that it couldn't find those packages in `/bin/sh` path but it should look for those inside `node_modules` if you did everything correct.

I'm sorry but it's a problem with Yarn and your `PATH` (environment variable) configuration rather than `Geluid` project.

I'm going to close this issue since this isn't a bug.
