### ISSUE TITLE
Windows build fails

### ISSUE THREAD

**Issue by OscarWoHA** [kulek1/Geluid#22]
Been trying to build this all day on Windows. I am not familiar with how node-gyp works at all, and couldn't solve this myself but would appreciate some help. The following is the console output of `yarn`

```
Building the projects in this solution one at a time. To enable parallel build, please add the "-m" switch.
  Copying lame/libmp3lame.dll to build/Release\libmp3lame.dll
          1 file(s) copied.
  Copying portaudio/bin/portaudio_x64.dll to build/Release\portaudio_x64.dll
          1 file(s) copied.
  naudiodon.cc
  GetDevices.cc
  AudioIn.cc
  AudioOut.cc
  win_delay_load_hook.cc
C:\Users\ohall\Documents\Development\For fun\Geluid\node_modules\naudiodon-lame\src\AudioIn.cc(25,10): fatal error C1083: Cannot open include file: 'lame/lame.h': No such file or directory [C:\Users\ohall\Documents\Development\For fun\Geluid\node_modules\naudiodon-lame\build\naudiodon-lame.vcxproj]
gyp ERR! build error
gyp ERR! stack Error: `C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\MSBuild\Current\Bin\MSBuild.exe` failed with exit 
code: 1
gyp ERR! stack     at ChildProcess.onExit (C:\Users\ohall\AppData\Roaming\nvm\v8.17.0\node_modules\npm\node_modules\node-gyp\lib\build.js:194:23)
gyp ERR! stack     at emitTwo (events.js:126:13)
gyp ERR! stack     at ChildProcess.emit (events.js:214:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:198:12)
gyp ERR! System Windows_NT 10.0.18362
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd C:\Users\ohall\Documents\Development\For fun\Geluid\node_modules\naudiodon-lame```

**Comment by kulek1** [comment]
Hey @OscarWoHA,
Unfortunately it's a problem with `naudiodon-lame` dependency on Windows. 
You can try to move `lame/lame.h` from `naudiodon-lame` (`node_modules`) to the `build` directory and try it again.
